name: Node.js CI

on:
  push:
    branches:
        - main
    
    tags-ignore:
      - '[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 19.x, 20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install git-flow (AVH)
        run: sudo apt install git-flow
      - run: git config --global user.email "gautamipatil2809@gmail.com"
      - run: git config --global user.name "Gautami2"
      - name: Install npm dependencies
        run: npm ci
      - name: Build project
        run: npm run build --if-present
      - name: Analyse project
        run: npm run lint
      - name: Test project
        run: npm test
